In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import  cosine_similarity
import re

In [2]:
fooData = pd.read_csv('C:\\Users\\shaar\\Downloads\\FoodReccSystem-main\\fooddataset.csv')

In [3]:
fooData.head()

Food_ID                  Name        C_Type  Veg_Non  \
0        1   summer squash salad  Healthy Food      veg   
1        2  chicken minced salad  Healthy Food  non-veg   
2        3  sweet chilli almonds         Snack      veg   
3        4       tricolour salad  Healthy Food      veg   
4        5        christmas cake       Dessert      veg   

                                            Describe  
0  white balsamic vinegar, lemon juice, lemon rin...  
1  olive oil, chicken mince, garlic (minced), oni...  
2  almonds whole, egg white, curry leaves, salt, ...  
3  vinegar, honey/sugar, soy sauce, salt, garlic ...  
4  christmas dry fruits (pre-soaked), orange zest...

In [4]:
fooData.shape

(400, 5)

In [5]:
fooData.isnull().sum()

Food_ID     0
Name        0
C_Type      0
Veg_Non     0
Describe    0
dtype: int64

In [6]:
#NO null values found in the given data set

#combining all the feature to a list format
combinedFeatures = fooData['Name'] +' ' +fooData['C_Type'] +' ' +fooData['Veg_Non'] +' ' +fooData['Describe']

In [7]:
print(combinedFeatures)

0      summer squash salad Healthy Food veg white bal...
1      chicken minced salad Healthy Food non-veg oliv...
2      sweet chilli almonds Snack veg almonds whole, ...
3      tricolour salad Healthy Food veg vinegar, hone...
4      christmas cake Dessert veg christmas dry fruit...
                             ...                        
395    Kimchi Toast Korean veg  cream cheese, chopped...
396    Tacos de Gobernador (Shrimp, Poblano, and Chee...
397    Melted Broccoli Pasta With Capers and Anchovie...
398    Lemon-Ginger Cake with Pistachios Dessert non-...
399    Rosemary Roasted Vegetables Healthy Food veg k...
Length: 400, dtype: object


In [8]:
print(combinedFeatures[21])

baked namak para Snack veg whole wheat flour (atta), refined flour (maida), baking powder, ghee, salt, carom seeds (ajwain)


In [9]:
#data cleaning 

In [10]:
# Assuming combinedFeatures is a list of strings
combinedFeatures = [feature.replace(',', '') for feature in combinedFeatures]
combinedFeatures = [feature.replace('"', '') for feature in combinedFeatures]
combinedFeatures = [feature.replace('(', '') for feature in combinedFeatures]
combinedFeatures = [feature.replace(')', '') for feature in combinedFeatures]

In [11]:
print(combinedFeatures)

['summer squash salad Healthy Food veg white balsamic vinegar lemon juice lemon rind red chillies garlic cloves crushed olive oil summer squash zucchini sea salt black pepper basil leaves', 'chicken minced salad Healthy Food non-veg olive oil chicken mince garlic minced onion salt black pepper carrot cabbage green onions sweet chilli sauce peanut butter ginger soy sauce fresh cilantro red pepper flakes crushed tarts', 'sweet chilli almonds Snack veg almonds whole egg white curry leaves salt sugar fine grain red chilli powder', 'tricolour salad Healthy Food veg vinegar honey/sugar soy sauce salt garlic cloves minced chilli pepper sliced green papaya carrot peeled cucumbers mint leaves toasted peanuts', 'christmas cake Dessert veg christmas dry fruits pre-soaked orange zest lemon zest jaggery syrup almond flour apple butter softened eggs', 'japanese curry arancini with barley salsa Japanese veg japanese curry sticky rice cheese inside rice barley salsa wasabi mayo red capsicum cube cut y

In [12]:
print(combinedFeatures[21])

baked namak para Snack veg whole wheat flour atta refined flour maida baking powder ghee salt carom seeds ajwain


In [13]:
vectorizer = TfidfVectorizer()

In [14]:
featureVector = vectorizer.fit(combinedFeatures)

In [15]:
featureVector = vectorizer.transform(combinedFeatures)

In [16]:
print(featureVector)

  (0, 1578)	0.21672680423048934
  (0, 1539)	0.1408361887720984
  (0, 1515)	0.16207486675856958
  (0, 1499)	0.04293276598916954
  (0, 1382)	0.4623449760544007
  (0, 1342)	0.4623449760544007
  (0, 1214)	0.19358619359555165
  (0, 1187)	0.07258456070891654
  (0, 1181)	0.17165503662913478
  (0, 1140)	0.24075265789776557
  (0, 1123)	0.10708083372373974
  (0, 1000)	0.10298890407781497
  (0, 915)	0.1223938756260615
  (0, 911)	0.07804368410233642
  (0, 755)	0.24343551020326892
  (0, 749)	0.12377892367428522
  (0, 680)	0.13063228735979865
  (0, 623)	0.12521014840455036
  (0, 551)	0.08690227789527216
  (0, 522)	0.1223938756260615
  (0, 387)	0.16565466986295033
  (0, 325)	0.14189631093010202
  (0, 293)	0.14524341554617612
  (0, 150)	0.11787045726282579
  (0, 107)	0.18400602372498642
  :	:
  (398, 680)	0.19854257381119597
  (398, 566)	0.3091611787768989
  (398, 518)	0.16647738515209679
  (398, 468)	0.20242005439741867
  (398, 426)	0.19488263945689752
  (398, 216)	0.2546721886957135
  (398, 206)	0.1

Generating similaity matrix score using Cosine Similarity

In [17]:
similarity = cosine_similarity(featureVector)

In [18]:
print(similarity)

[[1.         0.17949985 0.08158    ... 0.07411155 0.07377155 0.10273619]
 [0.17949985 1.         0.11949045 ... 0.10184851 0.06706992 0.15705625]
 [0.08158    0.11949045 1.         ... 0.02060648 0.07072647 0.01440608]
 ...
 [0.07411155 0.10184851 0.02060648 ... 1.         0.03865541 0.05588566]
 [0.07377155 0.06706992 0.07072647 ... 0.03865541 1.         0.00373781]
 [0.10273619 0.15705625 0.01440608 ... 0.05588566 0.00373781 1.        ]]


Generating a list with all movie titles of the Dataset

In [19]:
Listallfood = fooData['Name'].tolist()

In [20]:
print(Listallfood)

['summer squash salad', 'chicken minced salad', 'sweet chilli almonds', 'tricolour salad', 'christmas cake', 'japanese curry arancini with barley salsa', 'chocolate nero cookies', 'lamb and chargrilled bell pepper soup', 'cream of almond soup', 'broccoli and almond soup', 'coconut lime quinoa salad', 'lemon honey glazed sous vide corn on the cob', 'watermelon and strawberry smoothie', 'peach, raspberry and nuts smoothie', 'almond and cranberry poha', 'almond and raw banana galawat', 'baked namakpara with roasted almond dip', 'grilled almond barfi', 'baked shankarpali ', 'baked multigrain murukku', 'apple rabdi', 'baked namak para', 'dates and nuts ladoo', 'green lentil dessert fudge', 'cashew nut cookies', 'almond pearls', 'hawaiin papaya salad', 'vegetable som tam salad', 'spinach and feta crepes', 'couscous with ratatouille - tangy tomato sauce', 'baked almond kofta', 'almond and amaranth ladoo', 'moong dal kiwi coconut soup', 'mixed berry & banana smoothie', 'banana walnut smoothie'

In [21]:
#for testing let us take ip = 'Chana Masala'

In [22]:
ip = 'Chana masala'

In [23]:
#finding the closest match form the Listallfood to the ip

In [24]:
FindCloseMatch = difflib.get_close_matches(ip,Listallfood)

In [25]:
print(FindCloseMatch)

['Channa Masala', 'chicken masala', 'chicken tikka masala']


In [26]:
CloseMatch  = FindCloseMatch[0]

In [27]:
print(CloseMatch)

Channa Masala


finding the index of the movie based on the Name(closeMatch)

In [28]:
index_of_food = fooData[fooData['Name']==CloseMatch]['Food_ID'].values[0]
print(index_of_food)

346


In [29]:
similarity_score = list(enumerate(similarity[index_of_food]))

In [30]:
print(similarity_score)

[(0, 0.002816931921880873), (1, 0.01940869643901162), (2, 0.02132799805926147), (3, 0.0033903576031541907), (4, 0.002945042764516455), (5, 0.0016516915123987624), (6, 0.01675639638004699), (7, 0.04273141103761931), (8, 0.003045288986870264), (9, 0.003451610300344507), (10, 0.01295503523289712), (11, 0.010357815084169518), (12, 0.0035066390111293264), (13, 0.002150847565656335), (14, 0.0211299450302884), (15, 0.04162377237359684), (16, 0.0032744728126945545), (17, 0.004586046412967321), (18, 0.06492293732077659), (19, 0.03598440831941162), (20, 0.003677872633570852), (21, 0.017935368332199903), (22, 0.003039280952015209), (23, 0.003216481831710182), (24, 0.01252201727692799), (25, 0.10714988634679906), (26, 0.002575881942099015), (27, 0.0028584570956787024), (28, 0.10794423492976901), (29, 0.01601054618847555), (30, 0.05074333100628678), (31, 0.0034143316521750857), (32, 0.08160018775344657), (33, 0.0032790394193139383), (34, 0.0034659043526665927), (35, 0.0036050060110499006), (36, 0.0

In [31]:
sorted_similar_food = sorted(similarity_score,key =lambda x:x[1], reverse=True)

In [32]:
print(sorted_similar_food)

[(346, 1.0000000000000002), (342, 0.3891096217529986), (353, 0.3319026693638647), (347, 0.26066267735168847), (350, 0.2514654693613716), (348, 0.2279902901191554), (352, 0.21044465432181983), (161, 0.18985101037230281), (284, 0.18409532880780058), (315, 0.17106400474414654), (341, 0.16358311792074562), (363, 0.1621285477868697), (349, 0.15892707114654459), (259, 0.15325563977250034), (262, 0.1493858669216282), (152, 0.14399901402258652), (257, 0.14198734532362986), (38, 0.14002991942496817), (102, 0.1382441354502187), (332, 0.13790986254726806), (101, 0.1361806276796048), (159, 0.13540838205981945), (180, 0.13515327415634384), (77, 0.13462152218635381), (333, 0.1334590637920629), (99, 0.13250773259323056), (345, 0.13061786559091296), (319, 0.1304002693563867), (296, 0.1294968218590623), (354, 0.12650003511068536), (351, 0.11858811837004007), (211, 0.11704009398099394), (362, 0.1163801285314303), (40, 0.11609765932890972), (335, 0.1154811690892485), (114, 0.11503764354269924), (198, 0.1

Printing all the names of the Suggested Foods

In [33]:
# print('Suggested Foods are : ')
# i=1
# for food in soreted_similar_movie:
#     index = food[0]
    

#     title_from_index = fooData[fooData.Food_ID==index]['Name'].values[0]

#     if(i<30):
#         print(i, '.',title_from_index)
#         i+=1

print('Suggested Foods are:')
i = 1

for dish in sorted_similar_food:
    index = dish[0]
    
    # Filter fooData by Food_ID and retrieve the corresponding Name (if available)
    filtered_data = fooData[fooData.Food_ID == index]
    
    if not filtered_data.empty:
        title_from_index = filtered_data['Name'].iloc[0]  # Using .iloc[0] to access the first row's 'Name'
        print(i, '.', title_from_index)
        i += 1
        if i >= 31:
            break  # Exit the loop if we've printed 30 suggestions (starting from 1)
    else:
        print(f"No food found for Food_ID: {index}")

# If fewer than 31 suggestions were printed, you may want to handle this case separately
if i == 1:
    print("No suggestions available.")

Suggested Foods are:
1 . Channa Masala
2 . Mushroom Rice
3 . Hyakula
4 . Saag Alo 
5 . Jeera Alu
6 . Alo Tama Bodi
7 . Lamb Shashlik
8 . spanish fish fry
9 . strawberry quinoa pancakes
10 . Quinoa Bowl and Berries
11 . Cheese Naan
12 . Bao Bun 
13 . Tarka Daal
14 . ragi coconut ladoo (laddu)
15 . chicken masala
16 . prawn fried rice
17 . ragi oats ladoo (laddu)
18 . mixed salad with lotus root
19 . dahi chicken
20 . Mushroom Manchruian
21 . crispy herb chicken
22 . batter fish
23 . lotus leaf wrapped fried rice
24 . grilled lemon margarita
25 . Biryani
26 . spicy chicken masala
27 . Cucumber and Radish Salad
28 . Crispy Pakora
29 . tandoori fish tikka
30 . Alo Achar


FOOD RECC SYSTEM INTERACTIVE MODEL

In [35]:
foodName = input('Enter the Name of your Fav Dish :  ')
ListAlltitle = fooData['Name'].tolist()
FindCloseMatch = difflib.get_close_matches(foodName,ListAlltitle)
close_match = FindCloseMatch[0]
index_of_food = fooData[fooData.Name == close_match]['Food_ID'].values[0]
similarity_score = list(enumerate(similarity[index_of_food]))
sorted_similar_food = sorted(similarity_score, key =lambda x:x[1],reverse = True)


print('Suggested Foods are:')
i = 1

for dish in sorted_similar_food:
    index = dish[0]
    
    # Filter fooData by Food_ID and retrieve the corresponding Name (if available)
    filtered_data = fooData[fooData.Food_ID == index]
    
    if not filtered_data.empty:
        title_from_index = filtered_data['Name'].iloc[0]  # Using .iloc[0] to access the first row's 'Name'
        print(i, '.', title_from_index)
        i += 1
        if i >= 11:
            break  # Exit the loop if we've printed 30 suggestions (starting from 1)
    else:
        print(f"No food found for Food_ID: {index}")

# If fewer than 31 suggestions were printed, you may want to handle this case separately
if i == 1:
    print("No suggestions available.")


Enter the Name of your Fav Dish :   pizza


Suggested Foods are:
1 . filo pizza
2 . lemon poppy seed cake
3 . french pork chop
4 . mixed vegetable soup
5 . batter fish
6 . japanese curry arancini with barley salsa
7 . chicken parmigiana with tomato sauce
8 . dark night
9 . chocolate prunes gujiyas
10 . plum cake
